### ISSUE TITLE
 tuple index out of range

### ISSUE THREAD

**Issue by wangleiphy** [wangleiphy/jax-flow-matching#6]
[wanglei@node002 src]$ python ../src/inference.py --nlayers 4 --h1size 256 --h2size 64 --batchsize 100 --dataset ../data/LJSystem_npz/liquid/traj_N32_rho0.7_T1.0.npz --ferminet  --restore_path /data/wanglei/lj/npz/n_32_dim_3_lr_0.001_ferminet_l_4_h1_256_h2_64/

========== Prepare training dataset ==========
(10000, 96) 1.22250247459806
-0.09474517 1.309129
Load dataset: ../data/LJSystem_npz/liquid/traj_N32_rho0.7_T1.0.npz

========== Construct ferminet ==========
# of params: 464000

========== Prepare logs ==========
folder: /data/wanglei/lj/npz/n_32_dim_3_lr_0.001_ferminet_l_4_h1_256_h2_64
Load checkpoint file: /data/wanglei/lj/npz/n_32_dim_3_lr_0.001_ferminet_l_4_h1_256_h2_64/epoch_022000.pkl, epoch finished: 22000

========== Start inference ==========
sample shape (100, 5, 96)
data shape (10000, 96)
Traceback (most recent call last):
  File "/home/wanglei/jax-flow-matching/src/../src/inference.py", line 113, in <module>
    vfe, vfe_err = free_energy_fn(subkey, params, args.batchsize)
  File "/home/wanglei/jax-flow-matching/src/energy.py", line 111, in free_energy
    e = energy_fun(x)
  File "/home/wanglei/.local/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/wanglei/.local/lib/python3.9/site-packages/jax/_src/api.py", line 1680, in vmap_f
    out_flat = batching.batch(
  File "/home/wanglei/.local/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/wanglei/jax-flow-matching/src/energy.py", line 106, in energy_fun
    return lj_efunc(pos, box, jax_nblist(pos, box))
  File "/home/wanglei/jax-flow-matching/src/energy.py", line 96, in jax_nblist
    jax.ShapeDtypeStruct((160 * pos.shape[-2], 5), np.int32), 
jax._src.traceback_util.UnfilteredStackTrace: IndexError: tuple index out of range

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wanglei/jax-flow-matching/src/../src/inference.py", line 113, in <module>
    vfe, vfe_err = free_energy_fn(subkey, params, args.batchsize)
  File "/home/wanglei/jax-flow-matching/src/energy.py", line 111, in free_energy
    e = energy_fun(x)
  File "/home/wanglei/jax-flow-matching/src/energy.py", line 106, in energy_fun
    return lj_efunc(pos, box, jax_nblist(pos, box))
  File "/home/wanglei/jax-flow-matching/src/energy.py", line 96, in jax_nblist
    jax.ShapeDtypeStruct((160 * pos.shape[-2], 5), np.int32), 
IndexError: tuple index out of range

**Comment by wangleiphy** [comment]
fixed by 2887a5c6ce82fac54dcf03fa3c4cbd6980ae741f
